### ISSUE TITLE
Google Authentication: get access token ?

### ISSUE THREAD

**Issue by Raphaelbm** [NicklasWallgren/PokemonGoAPI-PHP#107]
Hello !

I try to sign in with my google account.

I can get all informations of the Google Account but i can't get a valide token to connect the user.

Example in Javascript:
`var profile = googleUser.getBasicProfile();
  console.log('ID: ' + profile.getId());
  console.log('Name: ' + profile.getName());
  console.log('Image URL: ' + profile.getImageUrl());
  console.log('Email: ' + profile.getEmail());
  var auth = googleUser.getAuthResponse();
  console.log("Token: "+auth.id_token);`

I don't know how to get the "AUTHENTICATION_REFRESH_TOKEN".

Can I get a good token with the id_token ? 

Edit: I will try in PHP.

**Comment by Raphaelbm** [comment]
I tried with the PHP Google library.

But my token is:

`{ "error": "unauthorized_client", "error_description": "Unauthorized" }`

My code:

`        $client = new Google_Client();
        $client->setAuthConfigFile('client_secret.json');
        $client->setScopes(array(
             'https://www.googleapis.com/auth/userinfo.email',
             'email',
             'openid',
        ));
        $client->setRedirectUri('http://' . $_SERVER['HTTP_HOST'] . '/profil/getToken.php');
        $auth_url = $client->createAuthUrl();
        header('Location: ' . filter_var($auth_url, FILTER_SANITIZE_URL));`

**Comment by DrDelay** [comment]
You shouldn't need to write code interacting with any authentication-libraries yourself, PTC and 3 types of Google Auth are all handled within this project.

Take a look at the [AuthenticationExample](https://github.com/NicklasWallgren/PokemonGoAPI-PHP/blob/master/examples/AuthenticationExample.php).

**Comment by TacoBytes** [comment]
When you go through Google and retrieve the authentication code, pass it to the `$config->setAuthToken('INSERT_AUTHENTICATION_CODE')`. After you do that, there is a refresh token, at least I see it when I do a `print_r($manager)`.

My issue, since am just learning how to work with classes/objects, is how can I get the protected refreshtoken value from the object shown when I print_r($manager). For example, this is what I get when I perform print_r($manager):

`NicklasW\PkmGoApi\Authentication\Managers\Google\AuthenticationCodeManager Object ( [authenticationCode:protected] => 4/v1WLDAhFHR4LgVJUHXn-cOuO-12345678901234 [listeners:protected] => Array ( [0] => Closure Object ( [parameter] => Array ( [$event] => [$value] => ) ) ) [accessToken:protected] => NicklasW\PkmGoApi\Authentication\AccessToken Object ( [token:protected] => 'intentionally removed text for this example' [timestamp:protected] => 1471199526 [refreshToken:protected] => 1/b9WjTyO65coDEnQ9S8S054jltTAU0VsaHgnY4WUFGnI [provider:protected] => google ) )`

**Comment by DrDelay** [comment]
Look at [this example](https://github.com/NicklasWallgren/PokemonGoAPI-PHP/blob/6c7ed40fc6ebd98b9cd932ca987dc1132e6297c8/examples/AuthenticationExample.php#L48-L59). Persist this `$accessToken`, it will also contain the refresh token and has a getter for it.

**Comment by Raphaelbm** [comment]
Ok thanks you ! It works ! :)

**Comment by vntopcoders** [comment]
@Raphaelbm 
Can you share with me your full source code of this feature?
