### ISSUE TITLE
Invalid authentication token & Response 502.

### ISSUE THREAD

**Issue by sensityy** [NicklasWallgren/PokemonGoAPI-PHP#17]
When I try to run the example's I either get 502 error or Invalid authentication token, 

any ideas?

Thanks

**Comment by NicklasWallgren** [comment]
What type of account are you using? PTC or Google?

**Comment by sensityy** [comment]
Tried both

**Comment by NicklasWallgren** [comment]
The invalid token error, is that related to the PTC account? Could to be the same issue as  https://github.com/NicklasWallgren/PokemonGoAPI-PHP/issues/7

**Comment by sensityy** [comment]
it happen on both AUTHENTICATION_TYPE_PTC is the right for PTC right?

**Comment by NicklasWallgren** [comment]
Exactly, have you used the account on the app before? Check @tomHash response in https://github.com/NicklasWallgren/PokemonGoAPI-PHP/issues/7

**Comment by sensityy** [comment]
yes, both GMAIL & PTC.. Hmm

**Comment by NicklasWallgren** [comment]
And the issue still remains in the latest release? I tested adding latitude and longitude, but it should not make any difference.

**Comment by sensityy** [comment]
I just downloaded the new version, not it's 30 second timeout

**Comment by paoloalby** [comment]
I have the same issue. Tried with both my account, PTC and Google, and I get this error

user@NAS:/volume1/web/_private/PokemonGoAPI-PHP-master/examples$ php RetrievePlayerProfile.php
PHP Fatal error:  Uncaught exception 'NicklasW\PkmGoApi\Handlers\RequestHandler\Exceptions\AuthenticationException' with message 'Invalid authentication token provided' in /volume1/web/_private/PokemonGoAPI-PHP-master/src/Handlers/RequestHandler.php:90
Stack trace:
#0 /volume1/web/_private/PokemonGoAPI-PHP-master/src/Handlers/RequestHandler.php(98): NicklasW\PkmGoApi\Handlers\RequestHandler->handle(Object(NicklasW\PkmGoApi\Requests\GetPlayerRequest))
#1 /volume1/web/_private/PokemonGoAPI-PHP-master/src/Services/Request/PlayerRequestService.php(20): NicklasW\PkmGoApi\Handlers\RequestHandler->handle(Object(NicklasW\PkmGoApi\Requests\GetPlayerRequest))
#2 /volume1/web/_private/PokemonGoAPI-PHP-master/src/Api/Player/Profile.php(37): NicklasW\PkmGoApi\Services\Request\PlayerRequestService->getPlayer()
#3 /volume1/web/_private/PokemonGoAPI-PHP-master/src/Api/Player/Profile.php(25): NicklasW\PkmGoApi\Api\Player\Profile->update()
#4 /volume1/web/_private/PokemonGoAPI-PHP-master/examples/RetrievePlayerProfile.php(27): NicklasW\PkmGoApi in /volume1/web/_private/PokemonGoAPI-PHP-master/src/Handlers/RequestHandler.php on line 90

**Comment by NicklasWallgren** [comment]
It would be helpful if you could send the log file to nicklas.wallgren@gmail.com

Thanks.


Could you please configure the LOG_FILE_PATH variable, and then

**Comment by NicklasWallgren** [comment]
I'm still working on this, hopefully we will find a solution soon. A big thanks to @paoloalby for helping me out with the debugging.

**Comment by NicklasWallgren** [comment]
Alright, the problem is probably due to PHP running as 32-bit. At this time the protocol buffer parser requires PHP running as 64-bit (or maybe PHP 7).

**Comment by jibarra-xx** [comment]
This issue is still being observed. Whenever I enter my gmail address and password in the examples, I get the Fatal Error below:

Fatal error: Uncaught NicklasW\PkmGoApi\Handlers\RequestHandler\Exceptions\AuthenticationException: Invalid authentication token provided in /homepages/26/d603489614/htdocs/pokemon/juan/PokemonGoAPI-PHP/src/Handlers/RequestHandler.php:113 Stack trace: #0 /homepages/26/d603489614/htdocs/pokemon/juan/PokemonGoAPI-PHP/src/Handlers/RequestHandler.php(124): NicklasW\PkmGoApi\Handlers\RequestHandler->handle(Object(NicklasW\PkmGoApi\Requests\GetInventoryRequest)) #1 /homepages/26/d603489614/htdocs/pokemon/juan/PokemonGoAPI-PHP/src/Services/Request/InventoryRequestService.php(20): NicklasW\PkmGoApi\Handlers\RequestHandler->handle(Object(NicklasW\PkmGoApi\Requests\GetInventoryRequest)) #2 /homepages/26/d603489614/htdocs/pokemon/juan/PokemonGoAPI-PHP/src/Api/Player/Inventory.php(129): NicklasW\PkmGoApi\Services\Request\InventoryRequestService->getInventory() #3 /homepages/26/d603489614/htdocs/pokemon/juan/PokemonGoAPI-PHP/src/Api/Player/Inventory.php(115): NicklasW\PkmGoApi\Api\Player\Inventory->update() #4 /homepages/26/d603489614 in /homepages/26/d603489614/htdocs/pokemon/juan/PokemonGoAPI-PHP/src/Handlers/RequestHandler.php on line 113

**Comment by NicklasWallgren** [comment]
@jibarra-xx Did you disable the 64-bit check?

**Comment by TacoBytes** [comment]
@NicklasWallgren yes, this was the reason why. Forgot to get back to you on this issue.
