### ISSUE TITLE
InvalidPathException with message 'Unable to read the environment file at .env

### ISSUE THREAD

**Issue by ArianR** [NicklasWallgren/PokemonGoAPI-PHP#22]
> Dotenv\Exception\InvalidPathException with message 'Unable to read the environment file at .../vendor/nicklasw/pkm-go-api/src/Kernels/../../.env.'

Why does the package use an .env file for the config variables? It makes it impossible to install the package with "composer require nicklasw/pkm-go-api". The only workaround to prevent this error is to modify files in composers vendor dir. Or do I miss something?

**Comment by DragonStar01** [comment]
see #6

**Comment by NicklasWallgren** [comment]
@arianrashidi: You are right, I will reconsider this.

**Comment by ArianR** [comment]
There is also a problem with the facades if you use it as an composer package. You could consider prefixing them with a namespace.

**Comment by NicklasWallgren** [comment]
@ArianR Due to the class alias?

**Comment by NicklasWallgren** [comment]
The environment file is now optional, and is referenced by file path.

**Comment by Ni42** [comment]
I wonder if it would be easier to just pass an array of options to the constructor instead of a file path? 

Then everyone could decide for himself if he wants a dotenv file, real environment variables, store the config in a php array or anything else when bootstrapping the Kernel. I mean, you are already passing three config options to it already anyways.

**Comment by ArianR** [comment]
@NicklasWallgren Yes, for example "src/Services/RequestService.php:38".

**Comment by NicklasWallgren** [comment]
@Ni42 Good idea, I will consider this for a upcoming release.

**Comment by NicklasWallgren** [comment]
I'm closing this issue. I will fix the Facades in upcoming commit.
