### ISSUE TITLE
How to get the movement string?

### ISSUE THREAD

**Issue by fgala** [NicklasWallgren/PokemonGoAPI-PHP#66]
Hey!

So far I've got a lot of the data of what I've needed but I just get a number when it comes to move1 and move2 of each pokemon.

Could you include an example of that?

Thanks!

**Comment by Gandaflux** [comment]
Use

``
$pokemon->getMove1String();
``

**Comment by fgala** [comment]
@Gandaflux thanks a lot for the reply.
In the src/Api/Pokemon/Pokemon.php I only see getMove1(), this gives me a string and it is working fine.
I do not see the getMove1String() and when I try $pokemon->getMove1String(); my app fails.

Where must I reference it from?

**Comment by Gandaflux** [comment]
Have you got latest version? Its in last commit. 

``
Api/Pokemon/Support/PokemonDetailsTrait
``

**Comment by fgala** [comment]
Oh I see that now, thanks!

BTW, obviously I'm new to OOP, how should I add this?

I referenced the trait to my class (I'm using the examples) with:

`use NicklasW\PkmGoApi\Api\Pokemon\Support\PokemonDetailsTrait;`

and then in the class I used the trait 

```
class example {
    use PokemonDetailsTrait;
```
but I'm not getting any response there either with `$pokemon->getMove1String();` .I mean, code works but I just don't get the strings.

Thanks for your help :)

**Comment by kronthto** [comment]
You shouldn't have to add the trait anywhere, it got added in efc868f198ad786f78a83c1b2ce0c4bd407c5e56, [here](https://github.com/NicklasWallgren/PokemonGoAPI-PHP/commit/efc868f198ad786f78a83c1b2ce0c4bd407c5e56#diff-ce841e912e7136bf552eba84702db7edR90). It certainly doesn't make sense in your example class.

What do you get when you do `var_dump($pokemon->getMove1String())`? It shouldn't be 'nothing' because of [this](https://github.com/NicklasWallgren/pogoprotos-php/blob/bfb3fce41ff37e8a39e115a20de2c838f3f70d38/src/POGOProtos/Enums/PokemonMove.php#L387).

**Comment by Gandaflux** [comment]
@fgala , check #71

**Comment by fgala** [comment]
Duh! My mad mates. Thanks @Gandaflux and @kronthto for pointing this out. As usual tried to do things far more complicated than it really is.

Thanks again, all working now.
