### ISSUE TITLE
Proper method to update

### ISSUE THREAD

**Issue by baskettcase** [NicklasWallgren/PokemonGoAPI-PHP#93]
What is the proper method to update? If I have done a git clone on my server and then I've added my own files.. do I just do another git clone in the same folder and it overwrites and then I need to do another composer update? or will that overwrite my additional files? I haven't edited core.

**Comment by Ni42** [comment]
You can just git pull again I think? Might be worth changing over to the composer install, see the current readme, then you can update by "composer update" ;)

**Comment by baskettcase** [comment]
Thanks @Ni42 Ill check out the composer install method, I didn't realize there was one!, that would indeed be a lot easier :)

**Comment by Ni42** [comment]
It got changed earlier today :)

**Comment by DrDelay** [comment]
With git you'd do `git fetch origin`, followed by a `git pull`. If you have local changes, though, there might be conflicts. 
You'll also have this conflicts with composer if you "add your own files", since you shouldn't do that in the vendor dir. 
Also, see [this](http://stackoverflow.com/a/15316602) on how to define a useful `git up`.

**Comment by baskettcase** [comment]
Thanks, I went with the composer method and no I don't add anything to the vendor directory. Im just talking about my own code using the libraries :) Although everything is broken right now until PHP 5.6 support comes back.

**Comment by DrDelay** [comment]
Good then, just wanted to pre-eliminate that. Having a examples folder inside this repo makes some people do such things I fear.

**Comment by NicklasWallgren** [comment]
Resolved.
