### ISSUE TITLE
Error with Google login : get_resource_type() expects parameter 1 to be resource, null given

### ISSUE THREAD

**Issue by paoloalby** [NicklasWallgren/PokemonGoAPI-PHP#97]
Yesterday everything worked well, but today if I try to login with Google Authentication Key, I'm encountering this error.

I tried from both my home webserver and from my domain [pogoinformer.com](http://www.pogoinformer.com/login.php).. same error.

With PTC login, it still works.

![immagine](https://cloud.githubusercontent.com/assets/15869726/17615010/41256b2a-606b-11e6-8bd7-8bc32654025e.png)

**Comment by paoloalby** [comment]
mhh, I tried with another google account, and it works.
It seems my account for now is "unreachable", because I can't login in game neither.

![file 12-08-16 09 12 54](https://cloud.githubusercontent.com/assets/15869726/17615234/248cdcf8-606d-11e6-83ce-24c34aa07052.png)

**Comment by Gandaflux** [comment]
Same here with one account. Probably we should make ticket on niantic support about it. 
It's your normal account, or botted ?

**Comment by paoloalby** [comment]
normal account.
Still can't login

**Comment by Gandaflux** [comment]
If its normal account you are safe, just make ticket on niantic support page that you cannot login on your phone into game.

https://support.pokemongo.nianticlabs.com/hc/en-us/articles/224047008

probably it's problem with their database, since for some accounts they return null inventory object. 

I have also problem with one account, but i use bot so complaining about that account maybe is not good idea ;-)

**Comment by NicklasWallgren** [comment]
@paoloalby Either the server is overloaded, or the account is banned.

**Comment by NicklasWallgren** [comment]
Resolved.
